name: traveltribe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  email_otp: ^3.1.0
  firebase_database: ^12.1.1
  cloud_firestore: ^6.1.1
  flutter_heatmap_calendar: ^1.0.1
  mailer: ^6.0.1
  url_launcher: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/TT_Logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/TT_Logo.png
